// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cifpoiugfrmkcdooefsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpZnBvaXVnZnJta2Nkb29lZnN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODA1MDMsImV4cCI6MjA3MTQ1NjUwM30.z5Dum6E10JSjeZoybdCSBG4CJ9kNW7-ca_k22biaU5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});